/**
 * Product Strategist Page (Agent 3)
 *
 * Creates master plan and implementation roadmap from the base prompt.
 * Produces TWO artifacts: Master Plan and Implementation Plan.
 *
 * USER FEELING: "I can see the plan before work starts."
 */

'use client';

import { useState } from 'react';
import { ApprovalButton } from '@/components/agents/ApprovalButton';
import { HashBadge } from '@/components/agents/HashBadge';

// Mock data - will be replaced with real API calls
const MOCK_BASE_PROMPT_HASH = 'b9d4e1f7c3a8d2e5';

const MOCK_MASTER_PLAN = `# Master Plan: Fitness Habit Tracker

## Overview
A web application focused on building lasting fitness habits through psychology-backed streak tracking and minimal-friction workout logging.

## Target Outcome
Users maintain consistent workout routines for 90+ days, forming permanent habits rather than temporary bursts of activity.

## Core Features

### 1. Workout Logging
- Quick-entry form (under 30 seconds)
- Workout type, duration, notes
- Today's workout prominent in UI
- Historical log with filters

### 2. Streak Tracking
- Current streak (days)
- Longest streak (personal record)
- Last workout timestamp
- Visual streak calendar

### 3. Progress Visualization
- Weekly consistency chart
- Monthly heatmap
- Workout frequency trends
- Achievement milestones

### 4. Habit Formation Support
- Daily reminders (configurable time)
- Motivational insights based on streak length
- Celebration of consistency milestones
- No judgment for missed days (restart mechanism)

## User Experience Principles

### Simplicity
Every screen serves one purpose. No feature creep.

### Speed
Logging a workout takes less than 30 seconds from app open to save.

### Motivation Without Pressure
Celebrate streaks, don't punish breaks. Recovery is part of the journey.

### Privacy First
No social features, no comparisons, no public data. This is personal growth only.

## Technical Foundation

### Frontend
- Next.js 14 (React framework)
- TypeScript for type safety
- Tailwind CSS for styling
- Responsive design (mobile-first)

### Backend
- RESTful API
- Authentication required (JWT or session-based)
- Database for user data, workouts, streaks

### Data Persistence
- User profiles
- Workout logs (date, type, duration, notes)
- Streak calculations (current, longest)
- Reminder preferences

## Success Metrics
- User retention at 30, 60, 90 days
- Average streak length
- Workout logging frequency
- Time to complete workout entry

## Non-Goals
- Social features (no sharing, no friends)
- Gamification beyond streaks (no badges, levels)
- Workout planning (no future scheduling)
- Nutrition tracking (fitness only)

---

**Generated by**: Product Strategist (Agent 3)
**Source**: Base Prompt (hash: b9d4e1f7c3a8d2e5)
**Authority**: PRODUCT_STRATEGY_AUTHORITY
`;

const MOCK_IMPLEMENTATION_PLAN = `# Implementation Plan: Fitness Habit Tracker

## Phase 1: Foundation (Core Data & Auth)

**Goal**: Users can create accounts and log in securely

### Steps
1. Set up authentication system (user registration, login, logout)
2. Create user profile data model
3. Implement password security (hashing, validation)
4. Build login/signup screens
5. Add session management

**Deliverables**: Working authentication, user accounts


## Phase 2: Workout Logging

**Goal**: Users can log workouts and view history

### Steps
1. Create workout data model (date, type, duration, notes)
2. Build workout entry form
3. Implement workout save API
4. Create workout history list view
5. Add date filtering

**Deliverables**: Functional workout logging system


## Phase 3: Streak Calculation

**Goal**: Users see their current and longest streaks

### Steps
1. Implement streak calculation logic
2. Store streak metadata (current, longest, last workout date)
3. Update streak on each workout log
4. Display streak prominently on dashboard
5. Handle streak reset when day missed

**Deliverables**: Real-time streak tracking


## Phase 4: Progress Visualization

**Goal**: Users see visual trends of their consistency

### Steps
1. Implement weekly consistency chart
2. Create monthly heatmap calendar
3. Add workout frequency statistics
4. Build achievement milestone system
5. Design progress dashboard

**Deliverables**: Visual progress tracking


## Phase 5: Reminders & Notifications

**Goal**: Users receive daily workout reminders

### Steps
1. Add reminder preference settings
2. Implement notification scheduling
3. Create reminder delivery system
4. Build notification management UI
5. Test reminder reliability

**Deliverables**: Configurable daily reminders


## Phase 6: Polish & Optimization

**Goal**: App is production-ready and performant

### Steps
1. Optimize database queries
2. Add loading states and error handling
3. Improve mobile responsiveness
4. Conduct user testing
5. Fix bugs and refine UX

**Deliverables**: Production-ready application


## Dependencies
- Phase 1 must complete before Phase 2
- Phase 2 must complete before Phase 3
- Phase 3 must complete before Phase 4
- Phase 4 and 5 can run in parallel
- Phase 6 requires all previous phases

## Estimated Complexity
- Phase 1: Medium (authentication is well-understood)
- Phase 2: Low (CRUD operations)
- Phase 3: Medium (date logic requires care)
- Phase 4: Medium (charting libraries)
- Phase 5: Low (notification APIs)
- Phase 6: Low (refinement)

---

**Generated by**: Product Strategist (Agent 3)
**Source**: Base Prompt (hash: b9d4e1f7c3a8d2e5)
**Authority**: PRODUCT_STRATEGY_AUTHORITY
`;

export default function ProductStrategistPage() {
  const [isLocked, setIsLocked] = useState(false);
  const [hash, setHash] = useState<string | null>(null);

  const handleApprove = async () => {
    // TODO: Call API to save both plans and lock
    console.log('Approving Master Plan and Implementation Plan');

    // Mock: Generate a hash and lock
    const mockHash = 'c4f8a2d9e7b1f3a6';
    setHash(mockHash);
    setIsLocked(true);

    // In real implementation, this would:
    // 1. POST /api/projects/:id/agents/product-strategist/approve
    // 2. Receive hash back
    // 3. Update agent state
    // 4. Unlock Screen Cartographer (Agent 4)
  };

  const handleReject = async () => {
    // TODO: Call API to revise
    console.log('Rejecting - must revise plans');
    alert('Rejection would require re-generation of plans from the base prompt.');
  };

  return (
    <div>
      {/* 1. CONTEXT HEADER */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <span className="text-4xl">📋</span>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Product Strategist</h1>
            <p className="text-gray-600 mt-1">Creates master plan and implementation roadmap</p>
          </div>
        </div>

        {hash && (
          <div className="mt-4">
            <HashBadge hash={hash} size="md" />
          </div>
        )}
      </div>

      {/* Authority Statement */}
      {!isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-blue-900">How this works</h3>
              <p className="text-sm text-blue-800 mt-1">
                This agent creates two strategic plans from your base prompt: a Master Plan (what to build) and
                an Implementation Plan (how to build it). It cannot add features, change scope, or make
                architectural decisions beyond what the base prompt specifies.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 2. INPUTS SECTION */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Input Source</h2>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded">
            <span className="text-xl">🤖</span>
            <span className="text-sm font-medium text-gray-700">Synthetic Founder</span>
          </div>
          <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          <HashBadge hash={MOCK_BASE_PROMPT_HASH} size="sm" />
        </div>
        <p className="text-sm text-gray-600 mt-3">
          This agent reads the approved base prompt from Synthetic Founder. It cannot access any other data.
        </p>
      </div>

      {/* 3. GENERATED ARTIFACTS (Read-Only) */}
      {/* Artifact 1: Master Plan */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Artifact 1: Master Plan</h2>
          <span className="text-xs text-gray-500 font-mono">Read-Only</span>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed">
            {MOCK_MASTER_PLAN}
          </pre>
        </div>

        <div className="mt-3 text-sm text-gray-600">
          {MOCK_MASTER_PLAN.length} characters • {MOCK_MASTER_PLAN.split('\n').length} lines
        </div>
      </div>

      {/* Artifact 2: Implementation Plan */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Artifact 2: Implementation Plan</h2>
          <span className="text-xs text-gray-500 font-mono">Read-Only</span>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed">
            {MOCK_IMPLEMENTATION_PLAN}
          </pre>
        </div>

        <div className="mt-3 text-sm text-gray-600">
          {MOCK_IMPLEMENTATION_PLAN.length} characters • {MOCK_IMPLEMENTATION_PLAN.split('\n').length} lines
        </div>
      </div>

      {/* 4. APPROVAL CONTROLS */}
      {!isLocked && (
        <div className="bg-white border-2 border-gray-200 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Do these plans accurately reflect your base prompt?
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            Once you approve, BOTH the Master Plan and Implementation Plan will be locked and hash-sealed. The next
            agent (Screen Cartographer) will use these plans to enumerate all screens in your app. If these plans
            don't match your intent, reject to revise.
          </p>

          <ApprovalButton
            onApprove={handleApprove}
            onReject={handleReject}
            approveText="Approve & Lock Both Plans"
            rejectText="Reject & Revise"
          />
        </div>
      )}

      {/* 5. STATE VISUALIZATION (Locked) */}
      {isLocked && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-6 h-6 text-green-600 flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-green-900">Plans Approved</h3>
              <p className="text-sm text-green-800 mt-1">
                Both plans have been approved and locked with hash: <code className="font-mono">{hash}</code>.
                The next agent (Screen Cartographer) will use these plans to map out all screens in your application.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 6. NEXT-AGENT UNLOCK */}
      {isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-3xl">🗺️</span>
              <div>
                <h3 className="font-semibold text-blue-900">Next: Screen Cartographer</h3>
                <p className="text-sm text-blue-800 mt-1">Will enumerate all screens in your app</p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-100 border border-amber-300 rounded-full">
              <span className="w-2 h-2 bg-amber-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-amber-700">Your Turn</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
