import type { FastifyInstance } from 'fastify';
import { validateCreateProjectInput } from '../models/index.js';
import type { ProjectService } from '../services/index.js';
import { NotFoundError, ValidationError } from '../utils/errors.js';
import archiver from 'archiver';
import { access, constants } from 'fs/promises';
import path from 'path';

/**
 * Project routes
 */
export async function projectRoutes(
  fastify: FastifyInstance,
  projectService: ProjectService
) {
  /**
   * POST /projects
   * Creates a new project
   */
  fastify.post('/projects', async (request, reply) => {
    if (!validateCreateProjectInput(request.body)) {
      throw new ValidationError(
        'Invalid input: name (1-255 chars) and description (max 5000 chars) are required'
      );
    }

    const project = await projectService.createProject(request.body);

    fastify.log.info({ projectId: project.id }, 'Project created');

    reply.code(201);
    return project;
  });

  /**
   * GET /projects
   * Retrieves all projects
   */
  fastify.get('/projects', async () => {
    const projects = await projectService.getAllProjects();
    return { projects };
  });

  /**
   * GET /projects/:id
   * Retrieves a specific project by ID
   */
  fastify.get<{ Params: { id: string } }>(
    '/projects/:id',
    async (request) => {
      const project = await projectService.getProjectById(request.params.id);

      if (!project) {
        throw new NotFoundError('Project', request.params.id);
      }

      return project;
    }
  );

  /**
   * GET /api/projects/:projectId/export.zip
   * Exports project workspace as ZIP file
   */
  fastify.get<{ Params: { projectId: string } }>(
    '/projects/:projectId/export.zip',
    async (request, reply) => {
      const { projectId } = request.params;

      // Verify project exists
      const project = await projectService.getProjectById(projectId);
      if (!project) {
        throw new NotFoundError('Project', projectId);
      }

      // Determine workspace directory path
      // This should point to where Forge assembles the project
      // For now, we'll use a placeholder path
      const workspaceDir = path.join(process.cwd(), 'workspaces', projectId);

      // Check if workspace exists
      try {
        await access(workspaceDir, constants.R_OK);
      } catch {
        reply.code(404);
        return {
          error: 'Workspace not found',
          details: `No assembled workspace found for project ${projectId}`,
        };
      }

      // Set response headers for ZIP download
      reply.header('Content-Type', 'application/zip');
      reply.header('Content-Disposition', `attachment; filename="project-${projectId}.zip"`);

      // Create ZIP archive
      const archive = archiver('zip', {
        zlib: { level: 9 }, // Maximum compression
      });

      // Handle errors
      archive.on('error', (err) => {
        fastify.log.error({ error: err, projectId }, 'ZIP archive error');
        throw err;
      });

      // Pipe archive to response
      archive.pipe(reply.raw);

      // Add workspace directory to archive
      archive.directory(workspaceDir, false);

      // Add README with project info
      const readme = `# Project: ${project.name}

${project.description || 'No description provided'}

## Exported from Forge

This project was assembled and verified by Forge.

- Project ID: ${projectId}
- Exported: ${new Date().toISOString()}

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Build for production:
   \`\`\`bash
   npm run build
   npm run start
   \`\`\`

## Verification

This project has passed all Forge verification checks.
See the verification reports in the build logs for full details.

---

Generated by Forge - Deterministic Application Assembly System
`;

      archive.append(readme, { name: 'FORGE-README.md' });

      // Finalize the archive
      await archive.finalize();

      fastify.log.info({ projectId }, 'Project workspace exported');
    }
  );
}
