/**
 * Screen Cartographer Page (Agent 4)
 *
 * Enumerates all application screens from the approved plans.
 * Produces ONE artifact: Screen Index (finite, complete list).
 *
 * USER FEELING: "These are all the screens. Nothing else will be built."
 */

'use client';

import { useState } from 'react';
import { ApprovalButton } from '@/components/agents/ApprovalButton';
import { HashBadge } from '@/components/agents/HashBadge';

// Mock data - will be replaced with real API calls
const MOCK_PRODUCT_STRATEGIST_HASH = 'c4f8a2d9e7b1f3a6';

const MOCK_SCREEN_INDEX = `# Screen Index: Fitness Habit Tracker

## Authentication Screens

### 1. Login Screen
**Purpose**: User authentication entry point
**Primary User**: Unauthenticated users
**Route**: /login

### 2. Sign Up Screen
**Purpose**: New user registration
**Primary User**: Unauthenticated users
**Route**: /signup

### 3. Forgot Password Screen
**Purpose**: Password reset initiation
**Primary User**: Unauthenticated users
**Route**: /forgot-password


## Core Application Screens

### 4. Dashboard
**Purpose**: Main home screen showing current streak and quick workout entry
**Primary User**: Authenticated users
**Route**: /dashboard

### 5. Log Workout Screen
**Purpose**: Quick workout entry form (target: under 30 seconds)
**Primary User**: Authenticated users
**Route**: /workouts/new

### 6. Workout History Screen
**Purpose**: View all logged workouts with filtering
**Primary User**: Authenticated users
**Route**: /workouts

### 7. Streak Calendar Screen
**Purpose**: Visual heatmap of workout consistency
**Primary User**: Authenticated users
**Route**: /streak

### 8. Progress Charts Screen
**Purpose**: Statistical visualization of fitness trends
**Primary User**: Authenticated users
**Route**: /progress

### 9. Settings Screen
**Purpose**: Configure reminders and account preferences
**Primary User**: Authenticated users
**Route**: /settings

### 10. Profile Screen
**Purpose**: View account details and overall stats
**Primary User**: Authenticated users
**Route**: /profile


## Screen Count Summary

**Total Screens**: 10
**Authentication Screens**: 3
**Core Application Screens**: 7

All screens are required by the approved Master Plan and Implementation Plan.
No additional screens will be added without restarting planning.

---

**Generated by**: Screen Cartographer (Agent 4)
**Source**: Master Plan + Implementation Plan (hash: c4f8a2d9e7b1f3a6)
**Authority**: STRUCTURE_DEFINITION_AUTHORITY
`;

export default function ScreenCartographerPage() {
  const [isLocked, setIsLocked] = useState(false);
  const [hash, setHash] = useState<string | null>(null);

  const handleApprove = async () => {
    // TODO: Call API to save screen index and lock
    console.log('Approving Screen Index');

    // Mock: Generate a hash and lock
    const mockHash = 'd7e3f9a1b8c4d2e6';
    setHash(mockHash);
    setIsLocked(true);

    // In real implementation, this would:
    // 1. POST /api/projects/:id/agents/screen-cartographer/approve
    // 2. Receive hash back
    // 3. Update agent state
    // 4. Unlock Journey Orchestrator (Agent 5)
  };

  const handleReject = async () => {
    // TODO: Call API to revise
    console.log('Rejecting - must revise screen index');
    alert('Rejection would require re-enumeration of screens from the approved plans.');
  };

  return (
    <div>
      {/* 1. CONTEXT HEADER */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <span className="text-4xl">🗺️</span>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Screen Cartographer</h1>
            <p className="text-gray-600 mt-1">Enumerates all application screens</p>
          </div>
        </div>

        {hash && (
          <div className="mt-4">
            <HashBadge hash={hash} size="md" />
          </div>
        )}
      </div>

      {/* Authority Statement */}
      {!isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-blue-900">How this works</h3>
              <p className="text-sm text-blue-800 mt-1">
                This agent enumerates every screen in your application from the approved Master Plan and
                Implementation Plan. It defines what screens exist, their canonical names, and their purpose. It
                cannot design screens, define flows, or add screens not specified in the plans.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 2. INPUTS SECTION */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Input Sources</h2>
        <div className="space-y-4">
          {/* Input 1: Master Plan */}
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded">
              <span className="text-xl">📋</span>
              <span className="text-sm font-medium text-gray-700">Product Strategist</span>
            </div>
            <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
            <HashBadge hash={MOCK_PRODUCT_STRATEGIST_HASH} size="sm" />
            <span className="text-sm text-gray-600">Master Plan</span>
          </div>

          {/* Input 2: Implementation Plan */}
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded">
              <span className="text-xl">📋</span>
              <span className="text-sm font-medium text-gray-700">Product Strategist</span>
            </div>
            <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
            <HashBadge hash={MOCK_PRODUCT_STRATEGIST_HASH} size="sm" />
            <span className="text-sm text-gray-600">Implementation Plan</span>
          </div>
        </div>
        <p className="text-sm text-gray-600 mt-4">
          This agent reads both approved plans from Product Strategist. Every screen must be traceable to these
          plans. It cannot access any other data.
        </p>
      </div>

      {/* 3. GENERATED ARTIFACT (Read-Only) */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Artifact: Screen Index</h2>
          <span className="text-xs text-gray-500 font-mono">Read-Only</span>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 max-h-[600px] overflow-y-auto">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed">
            {MOCK_SCREEN_INDEX}
          </pre>
        </div>

        <div className="mt-3 flex items-center justify-between text-sm text-gray-600">
          <span>
            {MOCK_SCREEN_INDEX.length} characters • {MOCK_SCREEN_INDEX.split('\n').length} lines
          </span>
          <span className="font-semibold">10 screens enumerated</span>
        </div>
      </div>

      {/* 4. APPROVAL CONTROLS */}
      {!isLocked && (
        <div className="bg-white border-2 border-gray-200 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Is this the complete list of screens for your application?
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            Once you approve, the Screen Index will be locked and hash-sealed. No new screens can be added without
            restarting planning. The next agent (Journey Orchestrator) will use this index to map user flows. If any
            screens are missing or should not be included, reject to revise.
          </p>

          <ApprovalButton
            onApprove={handleApprove}
            onReject={handleReject}
            approveText="Approve & Lock Screen Index"
            rejectText="Reject & Revise"
          />
        </div>
      )}

      {/* 5. STATE VISUALIZATION (Locked) */}
      {isLocked && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-6 h-6 text-green-600 flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-green-900">Screen Index Approved</h3>
              <p className="text-sm text-green-800 mt-1">
                The screen index has been approved and locked with hash: <code className="font-mono">{hash}</code>.
                The next agent (Journey Orchestrator) will use this index to map user flows between screens.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 6. NEXT-AGENT UNLOCK */}
      {isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-3xl">🔀</span>
              <div>
                <h3 className="font-semibold text-blue-900">Next: Journey Orchestrator</h3>
                <p className="text-sm text-blue-800 mt-1">Will map user flows between screens</p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-100 border border-amber-300 rounded-full">
              <span className="w-2 h-2 bg-amber-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-amber-700">Your Turn</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
