/**
 * Synthetic Founder Page (Agent 2)
 *
 * Converts Foundry Architect answers into a structured Base Prompt.
 * This agent has NO intelligence - it mechanically transforms answers into a prompt format.
 *
 * USER FEELING: "This reflects what I meant."
 */

'use client';

import { useState } from 'react';
import { ApprovalButton } from '@/components/agents/ApprovalButton';
import { HashBadge } from '@/components/agents/HashBadge';
import { useAgentState } from '@/lib/context/AgentStateContext';
import { useApproval } from '@/lib/hooks/useApproval';

// Mock data - will be replaced with real API calls
const MOCK_FOUNDRY_ANSWERS = {
  hash: 'fa8c7d2e9b1a4f6e',
  answers: {
    q1: 'Help users track their fitness goals and stay consistent with workouts',
    q2: 'Fitness enthusiasts aged 25-45 who struggle with consistency',
    q3: 'People start workout programs but quit after 2-3 weeks due to lack of motivation',
    q4: 'Workout logging, progress charts, streak tracking, daily reminders, habit formation insights',
    q5: 'User profiles, workout history, goals, achievements, streak data',
    q6: 'Yes, users need accounts to save their data across devices',
    q7: 'No, this is a single-user app focused on personal habit formation',
    q8: 'Focuses on building habits through psychology-backed streaks, not just tracking data',
  },
};

const MOCK_BASE_PROMPT = `# Base Prompt: Fitness Habit Tracker

## Purpose
Build a web application that helps users track their fitness goals and stay consistent with workouts through psychology-backed habit formation techniques.

## Target Users
- Fitness enthusiasts aged 25-45
- People who struggle with workout consistency
- Users who have quit previous workout programs after 2-3 weeks

## Core Problem
Users start workout programs but quit after 2-3 weeks due to lack of motivation and accountability. This app addresses the consistency gap through habit formation, not just data tracking.

## Key Features
1. **Workout Logging** - Quick entry of daily workouts
2. **Progress Charts** - Visual representation of fitness journey
3. **Streak Tracking** - Daily streak counter to build momentum
4. **Daily Reminders** - Timely notifications to maintain consistency
5. **Habit Formation Insights** - Psychology-backed feedback on habit patterns

## Data Model
- User profiles (authentication required)
- Workout history (date, type, duration, notes)
- Goals (target frequency, milestones)
- Achievements (badges, streaks)
- Streak data (current streak, longest streak, last workout date)

## Authentication
Users require accounts to save data across devices. Authentication will use industry-standard practices.

## Social Features
None. This is a single-user application focused on personal habit formation without social comparison or competition.

## Unique Value Proposition
Unlike generic fitness trackers that only log data, this app focuses on building lasting habits through:
- Streak-based motivation (don't break the chain)
- Psychology-backed insights on habit formation
- Minimal friction for daily logging
- Celebration of consistency over intensity

## Technical Constraints
- Web application (accessible from any device)
- Data must persist across sessions
- Real-time updates for streak calculations
- Mobile-responsive design

---

**Generated by**: Synthetic Founder (Agent 2)
**Source**: Foundry Architect answers (hash: fa8c7d2e9b1a4f6e)
**Authority**: SYNTHETIC_FOUNDER_AUTHORITY
`;

export default function SyntheticFounderPage() {
  // Get agent state from context
  const { currentState } = useAgentState('synthetic-founder');

  // Get approval functions
  const { approve, reject, isApproving, isRejecting, error } = useApproval(currentState?.approvalId);

  // Local UI state
  const [isLocked, setIsLocked] = useState(currentState?.status === 'approved');
  const [hash, setHash] = useState<string | null>(currentState?.hash || null);

  const handleApprove = async () => {
    const success = await approve();

    if (success) {
      // Update local state on success
      setIsLocked(true);
      // Hash will be available from updated agent state after refresh
    }
  };

  const handleReject = async () => {
    const confirmed = confirm('Are you sure you want to reject? This will require regenerating the base prompt.');

    if (!confirmed) return;

    await reject('User requested regeneration');
  };

  return (
    <div>
      {/* 1. CONTEXT HEADER */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <span className="text-4xl">🤖</span>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Synthetic Founder</h1>
            <p className="text-gray-600 mt-1">
              Converts your answers into a structured base prompt
            </p>
          </div>
        </div>

        {hash && (
          <div className="mt-4">
            <HashBadge hash={hash} size="md" />
          </div>
        )}
      </div>

      {/* Authority Statement */}
      {!isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-blue-900">How this works</h3>
              <p className="text-sm text-blue-800 mt-1">
                This agent mechanically converts your Foundry Architect answers into a structured prompt.
                It cannot invent features, change requirements, or add opinions. It only organizes your
                answers into a format that downstream agents can use.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 2. INPUTS SECTION */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Input Source</h2>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded">
            <span className="text-xl">🏗️</span>
            <span className="text-sm font-medium text-gray-700">Foundry Architect</span>
          </div>
          <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          <HashBadge hash={MOCK_FOUNDRY_ANSWERS.hash} size="sm" />
        </div>
        <p className="text-sm text-gray-600 mt-3">
          This agent reads your approved answers from Foundry Architect. It cannot access any other data.
        </p>
      </div>

      {/* 3. GENERATED ARTIFACT (Read-Only) */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Generated Base Prompt</h2>
          <span className="text-xs text-gray-500 font-mono">Read-Only</span>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed">
            {MOCK_BASE_PROMPT}
          </pre>
        </div>

        {/* Character Count */}
        <div className="mt-3 text-sm text-gray-600">
          {MOCK_BASE_PROMPT.length} characters • {MOCK_BASE_PROMPT.split('\n').length} lines
        </div>
      </div>

      {/* 4. APPROVAL CONTROLS */}
      {!isLocked && (
        <div className="bg-white border-2 border-gray-200 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Does this accurately reflect your vision?</h3>
          <p className="text-sm text-gray-600 mb-6">
            Once you approve, this base prompt will be locked and hash-sealed. The next agent (Product Strategist)
            will use this prompt to create your master plan. If this doesn't match your intent, reject it to revise
            your Foundry Architect answers.
          </p>

          {/* Error Display */}
          {error && (
            <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start gap-2">
                <svg className="w-5 h-5 text-red-600 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div className="flex-1">
                  <div className="font-semibold text-red-900">Approval Failed</div>
                  <div className="text-sm text-red-800 mt-1">{error}</div>
                </div>
              </div>
            </div>
          )}

          {/* No Approval ID Warning */}
          {!currentState?.approvalId && (
            <div className="mb-4 bg-amber-50 border border-amber-200 rounded-lg p-4">
              <div className="flex items-start gap-2">
                <svg className="w-5 h-5 text-amber-600 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div className="flex-1">
                  <div className="font-semibold text-amber-900">Not Ready for Approval</div>
                  <div className="text-sm text-amber-800 mt-1">
                    This agent has not yet generated an artifact awaiting approval. Complete the previous steps first.
                  </div>
                </div>
              </div>
            </div>
          )}

          <ApprovalButton
            onApprove={handleApprove}
            onReject={handleReject}
            approveText="Approve & Lock Base Prompt"
            rejectText="Reject & Revise"
            disabled={!currentState?.approvalId || isApproving || isRejecting}
          />
        </div>
      )}

      {/* 5. STATE VISUALIZATION (Locked) */}
      {isLocked && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-6 h-6 text-green-600 flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-green-900">Base Prompt Approved</h3>
              <p className="text-sm text-green-800 mt-1">
                Your base prompt has been approved and locked with hash: <code className="font-mono">{hash}</code>.
                The next agent (Product Strategist) will use this prompt to create your master plan.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 6. NEXT-AGENT UNLOCK */}
      {isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-3xl">📋</span>
              <div>
                <h3 className="font-semibold text-blue-900">Next: Product Strategist</h3>
                <p className="text-sm text-blue-800 mt-1">
                  Will create master plan and implementation roadmap
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-100 border border-amber-300 rounded-full">
              <span className="w-2 h-2 bg-amber-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-amber-700">Your Turn</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
