/**
 * Journey Orchestrator Page (Agent 5)
 *
 * Defines how users move through existing screens.
 * Produces ONE artifact: User Journeys (ordered paths).
 *
 * USER FEELING: "These are the only ways users move through the app."
 */

'use client';

import { useState } from 'react';
import { ApprovalButton } from '@/components/agents/ApprovalButton';
import { useAgentState } from '@/lib/context/AgentStateContext';
import { useApproval } from '@/lib/hooks/useApproval';
import { HashBadge } from '@/components/agents/HashBadge';

// Mock data - will be replaced with real API calls
const MOCK_SCREEN_INDEX_HASH = 'd7e3f9a1b8c4d2e6';

const MOCK_USER_JOURNEYS = `# User Journeys: Fitness Habit Tracker

## Journey 1: New User Registration

**User Role**: Unauthenticated users

### Path
1. Sign Up Screen
2. Dashboard

**Trigger**: User does not have an account
**End State**: User is authenticated and sees Dashboard


## Journey 2: Existing User Login

**User Role**: Unauthenticated users

### Path
1. Login Screen
2. Dashboard

**Trigger**: User has an account
**End State**: User is authenticated and sees Dashboard


## Journey 3: Password Reset

**User Role**: Unauthenticated users

### Path
1. Login Screen
2. Forgot Password Screen
3. Login Screen
4. Dashboard

**Trigger**: User cannot remember password
**End State**: User is authenticated with new password


## Journey 4: Log Daily Workout

**User Role**: Authenticated users

### Path
1. Dashboard
2. Log Workout Screen
3. Dashboard

**Trigger**: User wants to record a workout
**End State**: Workout is logged, Dashboard shows updated streak


## Journey 5: Review Workout History

**User Role**: Authenticated users

### Path
1. Dashboard
2. Workout History Screen

**Trigger**: User wants to see past workouts
**End State**: User views historical workout data


## Journey 6: View Streak Calendar

**User Role**: Authenticated users

### Path
1. Dashboard
2. Streak Calendar Screen

**Trigger**: User wants to see visual consistency heatmap
**End State**: User views monthly streak calendar


## Journey 7: View Progress Charts

**User Role**: Authenticated users

### Path
1. Dashboard
2. Progress Charts Screen

**Trigger**: User wants to see statistical trends
**End State**: User views charts and metrics


## Journey 8: Configure Settings

**User Role**: Authenticated users

### Path
1. Dashboard
2. Settings Screen
3. Dashboard

**Trigger**: User wants to enable reminders or change preferences
**End State**: Settings are saved, user returns to Dashboard


## Journey 9: View Profile

**User Role**: Authenticated users

### Path
1. Dashboard
2. Profile Screen

**Trigger**: User wants to see account details and overall stats
**End State**: User views profile information


## Journey 10: Settings to Profile

**User Role**: Authenticated users

### Path
1. Dashboard
2. Settings Screen
3. Profile Screen

**Trigger**: User navigates from Settings to Profile
**End State**: User views profile information


## Journey Summary

**Total Journeys**: 10
**Unauthenticated Journeys**: 3
**Authenticated Journeys**: 7

All journeys use only screens from the approved Screen Index.
All paths are ordered and explicit.
No conditional branching.

---

**Generated by**: Journey Orchestrator (Agent 5)
**Source**: Screen Index (hash: d7e3f9a1b8c4d2e6)
**Authority**: BEHAVIOR_DEFINITION_AUTHORITY
`;

export default function JourneyOrchestratorPage() {
  // Get agent state from context
  const { currentState } = useAgentState('journey-orchestrator');

  // Get approval functions
  const { approve, reject, isApproving, isRejecting, error } = useApproval(currentState?.approvalId);

  // Local UI state

  const [isLocked, setIsLocked] = useState(false);
  const [hash, setHash] = useState<string | null>(null);

  const handleApprove = async () => {
    const success = await approve();

    if (success) {
      setIsLocked(true);
    }
  };

  const handleReject = async () => {
    const confirmed = confirm('Are you sure you want to reject?');
    if (!confirmed) return;

    await reject('User requested regeneration');
  };

  return (
    <div>
      {/* 1. CONTEXT HEADER */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <span className="text-4xl">🔀</span>
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Journey Orchestrator</h1>
            <p className="text-gray-600 mt-1">Defines how users move through existing screens</p>
          </div>
        </div>

        {hash && (
          <div className="mt-4">
            <HashBadge hash={hash} size="md" />
          </div>
        )}
      </div>

      {/* Authority Statement */}
      {!isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-blue-900">How this works</h3>
              <p className="text-sm text-blue-800 mt-1">
                This agent defines explicit user journeys from the approved Screen Index. Each journey is an ordered
                path showing how users move between screens. It cannot create screens, design UI, or add conditional
                logic. All screen names must exactly match the Screen Index.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 2. INPUTS SECTION */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Input Source</h2>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-2 bg-gray-50 border border-gray-200 rounded">
            <span className="text-xl">🗺️</span>
            <span className="text-sm font-medium text-gray-700">Screen Cartographer</span>
          </div>
          <svg className="w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
          <HashBadge hash={MOCK_SCREEN_INDEX_HASH} size="sm" />
          <span className="text-sm text-gray-600">Screen Index (10 screens)</span>
        </div>
        <p className="text-sm text-gray-600 mt-3">
          This agent reads the approved Screen Index from Screen Cartographer. Every journey must use only screens
          from this index. It cannot access any other data.
        </p>
      </div>

      {/* 3. GENERATED ARTIFACT (Read-Only) */}
      <div className="bg-white border border-gray-200 rounded-lg p-6 mb-8">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold text-gray-900">Artifact: User Journeys</h2>
          <span className="text-xs text-gray-500 font-mono">Read-Only</span>
        </div>

        <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 max-h-[600px] overflow-y-auto">
          <pre className="whitespace-pre-wrap text-sm text-gray-800 font-mono leading-relaxed">
            {MOCK_USER_JOURNEYS}
          </pre>
        </div>

        <div className="mt-3 flex items-center justify-between text-sm text-gray-600">
          <span>
            {MOCK_USER_JOURNEYS.length} characters • {MOCK_USER_JOURNEYS.split('\n').length} lines
          </span>
          <span className="font-semibold">10 journeys defined</span>
        </div>
      </div>

      {/* 4. APPROVAL CONTROLS */}
      {!isLocked && (
        <div className="bg-white border-2 border-gray-200 rounded-lg p-6 mb-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-2">
            Do these journeys represent all user movement through your application?
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            Once you approve, all User Journeys will be locked and hash-sealed. User flows cannot be changed without
            restarting planning. The next agent (Visual Requirements Analyst) will use these journeys to define
            visual requirements. If any journeys are missing or incorrect, reject to revise.
          </p>

                    {/* Error Display */}
          {error && (
            <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start gap-2">
                <svg className="w-5 h-5 text-red-600 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div className="flex-1">
                  <div className="font-semibold text-red-900">Approval Failed</div>
                  <div className="text-sm text-red-800 mt-1">{error}</div>
                </div>
              </div>
            </div>
          )}

          <ApprovalButton
            onApprove={handleApprove}
            onReject={handleReject}
            approveText="Approve & Lock User Journeys"
            rejectText="Reject & Revise"
          />
        </div>
      )}

      {/* 5. STATE VISUALIZATION (Locked) */}
      {isLocked && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-8">
          <div className="flex gap-3">
            <svg
              className="w-6 h-6 text-green-600 flex-shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            <div>
              <h3 className="font-semibold text-green-900">User Journeys Approved</h3>
              <p className="text-sm text-green-800 mt-1">
                All user journeys have been approved and locked with hash: <code className="font-mono">{hash}</code>.
                The next agent (Visual Requirements Analyst) will use these journeys to define visual requirements
                for each screen.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* 6. NEXT-AGENT UNLOCK */}
      {isLocked && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-3xl">👁️</span>
              <div>
                <h3 className="font-semibold text-blue-900">Next: Visual Requirements Analyst</h3>
                <p className="text-sm text-blue-800 mt-1">Will define visual requirements for each screen</p>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-2 bg-amber-100 border border-amber-300 rounded-full">
              <span className="w-2 h-2 bg-amber-500 rounded-full animate-pulse" />
              <span className="text-sm font-medium text-amber-700">Your Turn</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
